name = "garden-planner"
compatibility_date = "2026-03-08"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "farming"
database_id = "bdaad09e-e5cb-4951-94fe-f5f8871ea7ff"
migrations_dir = "db/migrations"
